name: Deploy FastAPI App

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: cvoapi

jobs:
  build-and-install:
    name: Build & Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  deploy-to-cloudrun:
    name: Deploy to Cloud Run (Prod)
    runs-on: ubuntu-latest
    needs: build-and-install
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set GOOGLE_API_KEY environment variable
        run: echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> $GITHUB_ENV

      - name: Build and Push Docker image
        run: |
          gcloud builds submit --tag gcr.io/${{ env.PROJECT_ID }}/fastapi-image-personality .

      - name: Deploy to Google Cloud Run (using Docker image)
        run: |
          gcloud run deploy fastapi-image-personality \
            --image gcr.io/${{ env.PROJECT_ID }}/fastapi-image-personality \
            --region us-central1 \
            --platform managed \
            --set-env-vars GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}

      - name: Show Cloud Run URL
        run: |
          echo "Service URL:"
          gcloud run services describe fastapi-image-personality --region us-central1 --format 'value(status.url)'
